### ISSUE TITLE
Conditionals not supported: $gt, $gte, $lt, $lte, $mod..

### ISSUE THREAD

**Issue by kintel** [vkarpov15/mongoose-int32#1]
This type inherits directly from `mongoose.SchemaType` and thus doesn't support the mentioned conditionals, as they're implemented in `mongoose.NumberType`.

I notice that this package hasn't been updated in a while. Is there a recommended alternative to using this or is it just not common to work with integers in mongoose?

**Comment by kintel** [comment]
Update: I found mongoose-long to be significantly better maintained. Perhaps direct people there instead?

**Comment by vkarpov15** [comment]
Yeah int32 support for mongoose has always been an afterthought, not many use cases for it. This is a significant issue though, will fix ASAP

**Comment by vkarpov15** [comment]
Fixed in 0.2.0, please upgrade. 0.2.0 only supports mongoose >= 4.4.0 though :+1:
