### ISSUE TITLE
Allow users to specify the Mongoose instance they want to use

### ISSUE THREAD

**Issue by lantw44** [vkarpov15/mongoose-int32#9]
Both [mongoose-float](https://github.com/Vnkitaev/mongoose-float/blob/ad55d9141b6ba8a14c1cf3a5d38a95cf59717861/lib/index.js#L34) and [mongoose-long](https://github.com/mongoosejs/mongoose-long/blob/0.3.2/lib/index.js#L3) allow users to specify the Mongoose instance. Do you think it is good to allow it in mongoose-int32 as well?

**Comment by vkarpov15** [comment]
Yes it does make sense. We shouldn’t require it, but I think allowing it is useful

**Comment by Timmatt-Lee** [comment]
#10 try to support this
